### ISSUE TITLE
Updating Library Stops Midway

### ISSUE THREAD

**Issue by NoChain69** [Saud-97/TachiyomiS97#10] opened 2023-11-16 22:28 UTC
### Steps to reproduce

Scroll down on the Library Page to activate Update

### Expected behavior

It should go through every list of manga. For Example, (0/100), (1/100), (2/100)...(100/100)

### Actual behavior

It updates 1/4 of the list of mangas. (0/100), (1/100), (2/100)...(30/100) then stops.

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/Saud-97/TachiyomiS97/files/13384669/tachiyomi_crash_logs.txt)

### TachiyomiS97 version

1.7.3

### Android version

Android 10

### Device

Samsung J6

### Other details

I am really hating this bug, It used to work perfectly before (Probably during past versions), but now this is the problem I am facing

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.3](https://github.com/saud-97/TachiyomiS97/releases/latest)**.
- [X] I have updated all installed extensions.

**Comment by Saud-97** [comment] 2023-11-16 22:35
Can you explain more how does the updating stops? Does the app crash or does the notification just disappear silently. I suspect it might be because of battery saving features of your phone. 

The logs you shared also didn't include crash events trace.

**Comment by NoChain69** [comment] 2023-11-16 22:41
> Can you explain more how does the updating stops? Does the app crash or does the notification just disappear silently. I suspect it might be because of battery saving features of your phone.

No, the app stays up. The notification just disappears. 
Scenario:
When I update my library, it goes from (0/100) to (6/100) then finds a new chapter, then I update at that same time again it then goes from (0/100) to (7/100) then finds a new chapter of another manga. It used to go from (0/100) to (100/100).

Now its just stops at intervals. Ex. (0/100) to (15/100), (0/100) to (30/100), (0/100) to (6/100)

P.S battery saving is off for this app

**Comment by NoChain69** [comment] 2023-11-16 22:42
Sorry accidentaly closed it

**Comment by NoChain69** [comment] 2023-11-16 23:04
If possible, please tell me how should I resolve the problem?

**Comment by Saud-97** [comment] 2023-11-16 23:09
It appears this is a duplicate of #9 but you provided more information that helped me discover how to reproduce the bug.

Hopefully this will be fixed in the next release.

**Comment by NoChain69** [comment] 2023-11-16 23:11
Thanks for your patience, looking forward to the next release. Good Luck

**Closed** 2024-01-22 20:16 UTC
Labels: bug
